"""Value objects — data structures used across the agent pipeline and CLI."""

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from helixcode.core.entities import CodeSymbol


class ProblemSeverity(str, Enum):
    """Severity levels for code review findings."""

    CRITICAL = 'CRITICAL'
    WARNING = 'WARNING'
    SUGGESTION = 'SUGGESTION'


class Problem(BaseModel):
    """A single code review finding."""

    severity: ProblemSeverity
    file_path: str
    line: int | None = None
    message: str = Field(min_length=1)
    suggestion: str | None = None
    rule_name: str | None = None


class SearchResult(BaseModel):
    """Result from a semantic code search."""

    model_config = {'extra': 'ignore'}

    symbol_name: str
    symbol_kind: str
    file_path: str
    start_line: int
    end_line: int
    relevance_score: float = Field(ge=0.0, le=1.0)
    snippet: str = ''
    explanation: str | None = None


class TaskStep(BaseModel):
    """A single step in a task execution plan."""

    step_number: int = Field(ge=1)
    title: str = Field(min_length=1)
    description: str = ''
    target_file: str | None = None
    layer: str = ''
    dependencies: list[int] = Field(default_factory=list)


class TaskPlan(BaseModel):
    """Full task execution plan generated by the Planner node."""

    original_task: str = Field(min_length=1)
    steps: list[TaskStep] = Field(default_factory=list)
    estimated_complexity: str = 'medium'
    rationale: str | None = None
